client/urls.py
from django.urls import path
from client.apps import ClientConfig

from client.views import index, VideoView, download_video

app_name = ClientConfig.name


urlpatterns = [
    path('', index, name="index"),
    path('download/<int:pk>/', download_video, name='download_file'),
    path('videos/', VideoView.as_view(), name="videos"),
]

settings/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('client.urls', namespace='client')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

client/models.py
from django.db import models
import os


class ShortVideo(models.Model):
    name = models.CharField(max_length=42)
    text = models.TextField()
    content = models.FileField()

client/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views.generic import ListView

from converter.converter import get_video_from_text
from client.models import ShortVideo


def index(request):
    text = str(request.GET.get("text", ''))
    video = get_video_from_text(text)
    response_video = ShortVideo(name=video['name'], text=text, content=video['path'])
    response_video.save()
    return render(request, 'client/index.html', context={'object': response_video})



def download_video(request, pk):
    content = ShortVideo.objects.get(pk=pk)
    response = HttpResponse(content.content, content_type='application/force-download')
    response['Content-Disposition'] = f'attachment; filename="{content.content.name}"'
    return response


class VideoView(ListView):
    model = ShortVideo

    def get_queryset(self, *args, **kwargs):
        queryset = super().get_queryset(*args, **kwargs)
        print(queryset)
        return queryset

client/templates/client/index.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if object %}
    Видео: {{object.name}}  <a href="{% url 'client:download_file' object.pk %}">Скачать</a>
{% endif %}
<br>
<a href="{% url 'client:videos' %}">Все видео</a>
</body>
</html>

client/templates/client/shortvideo_list.html
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
{% if object_list %}
{% for object in object_list %}
    Видео: {{ object.name}}  <a href="{% url 'client:download_file' object.pk %}">Скачать</a>
    <br>
    {% endfor %}
{% else %}
Нет видео
{% endif %}
</body>
</html>